/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSuppliersRouteImport } from './routes/api/suppliers'
import { Route as ApiPartsRouteImport } from './routes/api/parts'
import { Route as ApiDiagnoseRouteImport } from './routes/api/diagnose'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuppliersRoute = ApiSuppliersRouteImport.update({
  id: '/api/suppliers',
  path: '/api/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartsRoute = ApiPartsRouteImport.update({
  id: '/api/parts',
  path: '/api/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnoseRoute = ApiDiagnoseRouteImport.update({
  id: '/api/diagnose',
  path: '/api/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnosis': typeof DiagnosisRoute
  '/parts': typeof PartsRoute
  '/report': typeof ReportRoute
  '/suppliers': typeof SuppliersRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
  '/api/parts': typeof ApiPartsRoute
  '/api/suppliers': typeof ApiSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnosis': typeof DiagnosisRoute
  '/parts': typeof PartsRoute
  '/report': typeof ReportRoute
  '/suppliers': typeof SuppliersRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
  '/api/parts': typeof ApiPartsRoute
  '/api/suppliers': typeof ApiSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnosis': typeof DiagnosisRoute
  '/parts': typeof PartsRoute
  '/report': typeof ReportRoute
  '/suppliers': typeof SuppliersRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
  '/api/parts': typeof ApiPartsRoute
  '/api/suppliers': typeof ApiSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnosis'
    | '/parts'
    | '/report'
    | '/suppliers'
    | '/api/diagnose'
    | '/api/parts'
    | '/api/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnosis'
    | '/parts'
    | '/report'
    | '/suppliers'
    | '/api/diagnose'
    | '/api/parts'
    | '/api/suppliers'
  id:
    | '__root__'
    | '/'
    | '/diagnosis'
    | '/parts'
    | '/report'
    | '/suppliers'
    | '/api/diagnose'
    | '/api/parts'
    | '/api/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosisRoute: typeof DiagnosisRoute
  PartsRoute: typeof PartsRoute
  ReportRoute: typeof ReportRoute
  SuppliersRoute: typeof SuppliersRoute
  ApiDiagnoseRoute: typeof ApiDiagnoseRoute
  ApiPartsRoute: typeof ApiPartsRoute
  ApiSuppliersRoute: typeof ApiSuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suppliers': {
      id: '/api/suppliers'
      path: '/api/suppliers'
      fullPath: '/api/suppliers'
      preLoaderRoute: typeof ApiSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parts': {
      id: '/api/parts'
      path: '/api/parts'
      fullPath: '/api/parts'
      preLoaderRoute: typeof ApiPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnose': {
      id: '/api/diagnose'
      path: '/api/diagnose'
      fullPath: '/api/diagnose'
      preLoaderRoute: typeof ApiDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosisRoute: DiagnosisRoute,
  PartsRoute: PartsRoute,
  ReportRoute: ReportRoute,
  SuppliersRoute: SuppliersRoute,
  ApiDiagnoseRoute: ApiDiagnoseRoute,
  ApiPartsRoute: ApiPartsRoute,
  ApiSuppliersRoute: ApiSuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
